var starter =document.querySelector(".starter")
var main =document.querySelector("#main")
var nameValue =document.querySelector("#name-value")
var startGame =document.querySelector("#start-game")
var userScore =document.querySelector("#user-score")
var botScore =document.querySelector("#computer-score")
var user =document.querySelector("#user")
var userName =document.querySelector("#user-name")
var userWin =document.querySelector("#user-winner")
var botWin =document.querySelector("#bot-winner")
var choiceUser=document.querySelector("#choice-user")
var choices =document.querySelector("#choices")
var choiceBot=document.querySelector("#choice-bot")
var scissor =document.querySelector("#scissor")
var paper =document.querySelector("#paper")
var rock =document.querySelector("#rock")
// console.log(starter)
// console.log(userScore)
// console.log(botScore)
// console.log(user)
// console.log(userName)
// console.log(userWin)
